source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gems.github.com"

gem "bundler"
gem "rake"
gem "em-serialport"
gem "eventmachine"
gem "serialport"
gem "ruby_protobuf"

gem "ruby-debug-base19x"
gem "ruby-debug-ide"
